apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: fraud-shield
  labels:
    app: fraud-shield
    component: api
spec:
  to:
    kind: Service
    name: fraud-shield
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
